"""add full_name column

Revision ID: 4d3bfc64ff32
Revises: cc338aaa7632
Create Date: 2025-04-24 16:03:48.704107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d3bfc64ff32'
down_revision: Union[str, None] = 'cc338aaa7632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    op.drop_table('ai_requests')
    op.drop_table('subscriptions')
    op.drop_table('entries')
    op.drop_table('promocodes')
    op.add_column('users', sa.Column('is_premium', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('weekly_requests', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('hearts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('total_requests', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_request_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('completed_challenges', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_challenge_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('active_challenge', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('challenge_started_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('extra_requests', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('referral_code', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('referred_by', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('ip_address', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('referral_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_referral_month', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('current_month_referrals', sa.Integer(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_column('users', 'notifications_enabled')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('notifications_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.alter_column('users', 'name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('users', 'current_month_referrals')
    op.drop_column('users', 'last_referral_month')
    op.drop_column('users', 'referral_count')
    op.drop_column('users', 'ip_address')
    op.drop_column('users', 'referred_by')
    op.drop_column('users', 'referral_code')
    op.drop_column('users', 'extra_requests')
    op.drop_column('users', 'challenge_started_at')
    op.drop_column('users', 'active_challenge')
    op.drop_column('users', 'last_challenge_time')
    op.drop_column('users', 'completed_challenges')
    op.drop_column('users', 'last_request_date')
    op.drop_column('users', 'total_requests')
    op.drop_column('users', 'hearts')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'weekly_requests')
    op.drop_column('users', 'is_premium')
    op.create_table('promocodes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('used_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['used_by'], ['users.telegram_id'], name='promocodes_used_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='promocodes_pkey'),
    sa.UniqueConstraint('code', name='promocodes_code_key')
    )
    op.create_table('entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], name='entries_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='entries_pkey')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('method', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('activated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], name='subscriptions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='subscriptions_pkey')
    )
    op.create_table('ai_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('model', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], name='ai_requests_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ai_requests_pkey')
    )
    op.create_table('logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='logs_pkey')
    )
    # ### end Alembic commands ###
